linters-settings:
  errcheck:
    check-type-assertions: true
  exhaustive:
    check-generated: true
    default-case-required: true
    default-signifies-exhaustive: true
    explicit-exhaustive-map: true
    explicit-exhaustive-switch: true
    package-scope-only: true
  godot:
    capital: true
  gosimple:
    go: "1.22"
  makezero:
    always: true
  staticcheck:
    checks: [all]
  stylecheck:
    checks: [all]

linters:
  enable:
    - asciicheck
    - containedctx
    - decorder
    - dogsled
    - dupl
    - errcheck # default
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - gci
    - godot
    - goerr113
    - goimports
    - goprintffuncname
    - gosec
    - gosimple # default
    - govet # default
    - ineffassign # default
    - ireturn
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - staticcheck # default
    - stylecheck
    - tagliatelle
    - tenv
    - tparallel
    - typecheck # default
    - unconvert
    - unparam
    - unused # default
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
