name: Go

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
